CREATE SEQUENCE GEN_KONTO_ID;

SET TERM ^ ;

CREATE TRIGGER Konto_BI FOR Konto
ACTIVE BEFORE INSERT POSITION 0
AS
BEGIN
  IF (new.nummer IS NULL) THEN
    new.nummer = GEN_ID(GEN_KONTO_ID,1);
END^

SET TERM ; ^

