CREATE SEQUENCE GEN_KOSTEN_ID;

SET TERM ^ ;

CREATE TRIGGER Kosten_BI FOR Kosten
ACTIVE BEFORE INSERT POSITION 0
AS
BEGIN
  IF (new.nummer is null) THEN
    new.nummer = GEN_ID(GEN_KOSTEN_ID,1);
END^

SET TERM ; ^

