CREATE SEQUENCE GEN_EINSTELLUNGEN_ID;

SET TERM ^ ;

CREATE TRIGGER Einstellungen_BI FOR Einstellungen
ACTIVE BEFORE INSERT POSITION 0
AS
BEGIN
  IF (new.nummer IS NULL) THEN
    new.nummer = GEN_ID(GEN_EINSTELLUNGEN_ID,1);
END^

SET TERM ; ^

