CREATE SEQUENCE GEN_UNTERKONTO_ID;

SET TERM ^ ;

CREATE TRIGGER UnterKonto_BI FOR UnterKonto
ACTIVE BEFORE INSERT POSITION 0
AS
BEGIN
  IF (new.nummer is null) THEN
    new.nummer = GEN_ID(GEN_UNTERKONTO_ID,1);
END^

SET TERM ; ^